### ISSUE TITLE
Existing documentation renders this project nearly unusable

### ISSUE THREAD

**Issue by russfellows** [openhistogram/circonusllhist#28]
Utilizing open source tools requires some rudimentary level of documentation.  The existing documentation is completely insufficient to enable use of this project.  Potential users are directed to read the C library comments as "documentation", which is disengenous at best, as the functions and API's between the C library and Golang implementation are significantly different.  

If the posters have any realistic intention of someone using this library, then basic documentation of functions, along with suggestions and examples of their use is required.  As currently provided, this project serves to enable the claim of "Open Source" in name only, while failing misearably to meet the objective of open source by witholding all information necessary to render this as a usable or useful project.

**Comment by bdunavant** [comment]
Hi there!   I think the godoc link on the Readme ( https://godocs.io/github.com/openhistogram/circonusllhist ) provides much of what you are looking for.   Hope this helps!   The main README has examples of general usage.   This has been sufficient for most existing users of the project, but could certainly be improved!

I am unsure where users are being directed at the C library, can you help me understand what you mean there?

**Comment by russfellows** [comment]
Yes, this link is a significant help.  I searched and could not find this link anywhere within the circonusllhist go repo.  Thank you for the professional response to my frustrated post.  Perhaps a direct link on the golang repo to this, or am I just not seeing something that is obvious to others?

From your very limited examples provided, I was able to figure out how to create and utilize very basic functionality of the golang library.  However, I would imagine that few potential users could glean an understanding of all the functions given there are no examples. 

For example, it is not at all clear how time would get associated with values.  I see the “RecordDuration()” and the “RecordValue()” functions, but how are they related correlated?  What would a “RecordIntScale()” be used for?  

Then all the “Serialize, Deserialize, Marshall, Unmarshall, DecToStrings, NewFromStrings” etc. etc. which are not exactly self documenting.  

I know it takes time, but any very simple programmatic examples of actually using these functions would make the library SIGNIFICANTLY more useful to many.  

As for my reference to the C library, in searching for documentation, I saw the link to that project from the golang rep, and then on that projects repo page, it described how to generate the docs from the header comments.  SInce that was the only documentation I could find, I assumed incorrectly that was the only documentation for the golang library.


--Russ

Russell Fellows
Senior Partner
Evaluator Group Inc.
(w) 303-221-7867 x1001
(c) 303-915-0445
***@***.***

**Comment by bdunavant** [comment]
Direct links to godoc are now on the README directly, which should help those that aren't familiar with the godoc icons.

While improved docs are always a benefit to all projects, this is sufficient to address the immediate bump hit, so I'm going to close this issue.

PR's are welcome from the community are further improvements.
